version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: greenspace-mysql
    restart: no
    environment:
      MYSQL_DATABASE: greenspace_db
      MYSQL_ROOT_PASSWORD: SpringBoot2026
    ports:
      - "3306:3306"
    volumes:
      - greenspace_db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - greenspace-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSpringBoot2026" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:alpine
    container_name: greenspace-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - greenspace-network

  backend:
    build: .
    container_name: greenspace-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/greenspace_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=SpringBoot2026
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=60000
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - greenspace-network

  prometheus:
    image: prom/prometheus:latest
    container_name: greenspace-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - greenspace-network
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: greenspace-alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - greenspace-network
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: greenspace-loki
    ports:
      - "3100:3100"
    networks:
      - greenspace-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: greenspace-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
    networks:
      - greenspace-network
    restart: unless-stopped

volumes:
  greenspace_db_data:
    driver: local

networks:
  greenspace-network:
    driver: bridge